os: Visual Studio 2015

environment:
  matrix:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Debug
    - platform: x64
      configuration: Release

matrix:
  fast_finish: false

build_script:
  - mkdir build && cd build
  - cmake .. -DARGON2_OPTIMIZATIONS=OFF
  - cmake --build . --config %CONFIGURATION%
  - ctest . -C %CONFIGURATION% -VV
  - cmake .. -DARGON2_OPTIMIZATIONS=ON
  - cmake --build . --config %CONFIGURATION%
  - ctest . -C %CONFIGURATION% -VV
